TRI_LAYER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
OS_DETECTION_ENABLE = yes
WPM_ENABLE = yes
LTO_ENABLE = yes
# TAP_DANCE_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no

INTROSPECTION_KEYMAP_C = hungps.c
SRC += oneshot.c oled.c encoder.c

